config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmations: "confirmations"}
  scope "(:locale)", locale: /en|vi/ do
    get "/pages/*page" => "pages#show"
    root "pages#show", page: "home"

    resources :users
    resources :orders
    resources :carts
    resources :charges
    resources :products do
      resources :order_details, only: :create
    end
    resources :order_details, only: %i(show destroy edit update)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: %i(accept waiting not_done)
  enum status_payment: %i(paid unpaid)

  belongs_to :user

  has_many :order_details, dependent: :destroy, as: :cart_order
  has_many :products, through: :order_details, dependent: :destroy

  accepts_nested_attributes_for :order_details, allow_destroy: true

  ATTRIBUTE_PARAMS = %i(user_id status status_payment).freeze

  scope :shopping_cart, ->(user_id){where(user_id: user_id)}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  attr_reader :order, :orders
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    page_params = params[:page]
    per_page = Settings.page.per_page
    @orders =
      if current_user.seller?
        Order.paginate page: page_params, per_page: per_page
      else
        Order.shopping_cart(current_user).paginate page: page_params,
          per_page: per_page
      end
  end

  def show; end

  def new; end

  def create
    order = Order.new order_params
    current_cart.order_details.each do |item|
      order.order_details << item
    end
    order_save order
  end

  def update
    if order.update_attributes order_params
      respond_to do |format|
        format.js
        format.html
      end
    else
      flash.now[:warning] = t "update_fail"
      render :index
    end
  end

  def destroy
    if order.destroy
      flash[:success] = t "destroy_succ"
      redirect_to user_orders_path
    else
      flash[:danger] = t "delete_fail"
      redirect_to root_path
    end
  end

  private

  def order_params
    params.require(:order).permit Order::ATTRIBUTE_PARAMS
  end

  def order_save order
    if order.save
      flash[:success] = t "order_success"
      redirect_to order_path order
    else
      render :new
      flash[:danger] = t "create_fail"
    end
  end
end

app/views/orders/_form.html.erb
<div class="format-login container">
  <%= form_for [product, order], local: true do |form| %>

    <div class="field">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.label :name, value: current_user.name %>
    </div>

    <div class="field">
      <%= form.label :room %>
      <%= form.label :room, value: current_user.room %>
    </div>

    <div class="field">
      <%= form.hidden_field :status, value: "not_done" %>
    </div>

    <div class="field">
      <%= form.hidden_field :status_payment, value: "unpaid" %>
    </div>

    <div class="actions">
      <%= form.submit t("buy"), class: "btn btn-add"%>
    </div>
  <% end %>
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :status, "not_done" %>
      <%= hidden_field_tag :status_payment, "paid" %>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="A month's subscription" data-locale="auto"></script>
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class="left-sidebar">
  <h2 style="font-size: 24px;"><%= t "edit" %></h2>
</div>

<%= render "form", order: @order %>
<br/>
<%= link_to t("back"), products_path,
  class: "btn btn-info" %>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
  <p><%= t "name" %><%= order.user.name %></p>
  <p><%= t "items" %></p>
  <ul>
    <% order.order_details.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
  <% if current_user.seller? != (@user == current_user) %>
    <div id="update_order">
      <%= form_for order, remote: true do |f| %>
        <div class="field" style="width: 80px;">
          <%= f.select :status, status_choice %>
          <%= f.submit t("change"), class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p><%= t "status" %><%= order.status %></p>
  <% end %>
  <p><%= t "status_payment" %><%= order.status_payment %></p>
<% end %>
<%= will_paginate %>

app/views/orders/new.html.erb
<div class="left-sidebar">
  <h2 style="font-size: 24px; font-family: lato">Chọn phương thức thanh toán</h2>
</div>
<div class="line">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="">
        <div class="form-order">
          <%= render "form", order: @order, product: @product %>
        </div>
      </div>
    </div>
</div>

app/views/orders/show.html.erb
<div class="col-sm-offset-2 col-sm-8 form-sign">
<div class="row">
<p style="margin-left: 20px; color: black">Khách hàng: <%= @order.user.name %></p>
<p style="margin-left: 20px; color: black">Phòng: <%= @order.user.room %></p>
</div>
  <% @order.order_details.each do |item| %>
  <div class="row">
      <div class="project-wrap size-d">
        <div class="project-thumbnail col-sm-5">
          <%= image_tag item.product.picture.url if item.product.picture? %>
        </div>
        <div class="col-sm-7">
          <div class="row">
          <div class="prd col-sm-11" style="color: #333"><%= item.product.name %> x <%= item.quantity %>
          <b class="pull-right">
            <%= number_with_delimiter(item.product_price * item.quantity) %> VNĐ</b>
          </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div>
<p style="margin-left: 550px; color: #333; background: #ddd; border-radius: .25rem; padding-left: 15px; padding-right: 15px;">
  Total: <b><%= number_with_delimiter(@order.sub_total) %> VNĐ</b></p></div>
</div>

app/views/orders/update.js.erb
$("#update_order").html("<%= escape_javascript(render('orders/index')) %>");