config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmations: "confirmations"}
  scope "(:locale)", locale: /en|vi/ do
    get "/pages/*page" => "pages#show"
    root "pages#show", page: "home"

    resources :users
    resources :orders
    resources :carts
    resources :charges
    resources :products do
      resources :order_details, only: :create
    end
    resources :order_details, only: %i(show destroy edit update)
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :order_details, dependent: :destroy, as: :cart_order
  has_many :products, through: :order_details, dependent: :destroy

  def sub_total
    sum = 0
    order_details.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = current_cart
  end

  def destroy
    if current_cart.destroy
      flash[:success] = t "destroy_succ"
      session[:cart_id] = nil
    else
      flash[:danger] = t "destroy_fail"
    end
    redirect_to root_path
  end
end

app/views/carts/_count.html.erb
<div class="lux"><%= count_order_details %></div>

app/views/carts/_form.html.erb
<%= form_for order_detail, remote: true do |f| %>
<%= f.submit t("add_one"), class: "btn btn-default" %>
<%= f.submit t("sub_one"), class: "btn btn-default" %>
<% end %>

app/views/carts/index.html.erb
<table>
  <thead>
    <tr>
      <th>Tên sản phẩm</th>
      <th>Giá (VNĐ)</th>
      <th style="padding-left: 42px">Số lượng</th>
      <th>Tổng (VNĐ)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.product.name %></td>
      <td><%= number_with_delimiter(order_detail.product.price) %></td>
        <td>
          <%= form_for order_detail, remote: true do |f| %>
            <%= f.submit t("sub_one"), class: "btn btn-default", style: "margin-right: 11px; height: 10%;" %>
            <%= order_detail.quantity %>
            <%= f.submit t("add_one"), class: "btn btn-default", style: "margin-left: 11px; height: 10%;" %>
          <% end %>
        </td>
        <td><%= number_with_delimiter(order_detail.total_price) %></td>
        <td>
          <%= link_to "Xóa", order_detail_path(order_detail),
            method: :delete, class: "btn btn-add", style: "background: #fa3600" %>
        </td>
        </tr>
    <% end %>
    <tr>
      <td>Tổng giá đơn hàng</td>
      <td></td>
      <td></td>
      <td><strong><%= number_with_delimiter(@carts.sub_total) %> VNĐ</strong></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
<div class="row">
<%= link_to "Thanh toán", new_order_path, class: "btn btn-add" %><br>
<p class="pull-right">
<%= link_to "Xóa đơn hàng", cart_path(current_cart),method: :delete,
  data: {confirm: t("confirm")}, class: "btn btn-add1" %></p>
</div>