config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {confirmations: "confirmations"}
  scope "(:locale)", locale: /en|vi/ do
    get "/pages/*page" => "pages#show"
    root "pages#show", page: "home"

    resources :users
    resources :orders
    resources :carts
    resources :charges
    resources :products do
      resources :order_details, only: :create
    end
    resources :order_details, only: %i(show destroy edit update)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  ATTRIBUTE_PARAMS =
    [
      :id, :name, :description, :user_id, :price, :picture, :category_id,
      :begin_at, :finish_at, :auto_close,
      areas_products_attributes: %i(id product_id area_id _destroy)
    ].freeze

  belongs_to :category
  belongs_to :user

  has_many :areas_products, dependent: :destroy
  has_many :areas, ->{distinct}, through: :areas_products, dependent: :destroy
  has_many :order_details, dependent: :destroy, as: :cart_order
  has_many :orders, through: :order_details, dependent: :destroy
  has_many :carts, through: :order_details, dependent: :destroy

  accepts_nested_attributes_for :areas_products, allow_destroy: true,
    reject_if: proc{|attributes| attributes["area_id"] == "0"}

  mount_uploader :picture, PictureUploader
  validate :picture_size
  validates :name, presence: true

  scope :product_by_time,
    ->{where "? BETWEEN begin_at AND finish_at", Time.zone.now}
  scope :product_by_area,
    ->(area_id){joins(:areas_products).where areas_products: {area_id: area_id}}
  scope :product_auto_close,
    ->{where auto_close: true}
  scope :product_by_category,
    ->(category_id){where(category_id: category_id)}
  scope :product_of_seller, ->(user_id){where(user_id: user_id)}

  private

  def picture_size
    return unless picture.size > Settings.picture.size.megabytes
    errors.add :picture, t("size")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  attr_reader :product, :products, :categories, :search

  load_and_authorize_resource
  before_action :authenticate_user!

  before_action :reset_area, only: :index

  def index
    @categories = Category.all
    @search = Product.ransack params[:q]
    @products =
      if current_user.seller?
        current_user.products
      else
        search.result.product_by_time.product_by_area(current_user.area_id).product_by_category(@categories)
      end
  end

  def new
    @areas = Area.all
  end

  def create
    if product.save
      flash[:info] = t "create_succ"
      redirect_to products_path
    else
      flash.now[:warning] = t "create_fail"
      render :new
    end
  end

  def show; end

  def edit
    @areas = Area.all
  end

  def update
    if product.update_attributes product_params
      flash[:info] = t "update_succ"
      redirect_to products_path
    else
      flash.now[:warning] = t "update_fail"
      render :edit
    end
  end

  def destroy
    product.destroy
    flash[:success] = t "destroy_succ"
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit Product::ATTRIBUTE_PARAMS
  end

  def reset_area
    if Time.now.strftime("%H:%M:%S") >= "23:00:00"
      Product.product_auto_close.each do |product|
        product.areas_products.destroy_all
        product.areas_products.create(product_id: product.id,
          area_id: product.user.area_id)
      end
    end
  end
end

app/views/products/_form.html.erb
<div class="container">
<div class="col-sm-offset-1 col-sm-10 form-sign">
  <%= form_for product, local: true, class: "form-signin" do |form| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="avatar-upload">
          <div class="avatar-edit">
            <%= form.file_field :picture, accept: "image/jpeg,image/gif,image/png", id: "imageUpload" %>
            <label for="imageUpload"></label>
          </div>
          <div class="avatar-preview">
            <div id="imagePreview" style="background-image: url(https://www.retailnews.asia/wp-content/uploads/2017/07/Ksubaka-Pasta.jpg);">
            </div>
          </div>
        </div>
      </div>

        <div class="field">
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>

      <div class="col-sm-6">
        <div class="field">
          <%= form.label :name, "Tên sản phẩm" %>
          <%= form.text_field :name, autofocus: true, class: "form-control" %>
        </div>

        <div class="field">
          <%= form.label :description, "Mô tả" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div class="field">
          <%= form.label :price, "Giá sản phẩm" %><br/>
          <%= form.number_field :price, label: false, class: "form-control" %>
        </div>

        <div class="row">

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <div class="field">
          <%= form.label :category_id, "Loại sản phẩm" %><br/>
          <%= form.select :category_id, category_choices, class: "select" %>
        </div>
      </div>

      <div class="col-sm-4" style="padding-left: 47px">
        <div class="field">
          <%= form.label :auto_set_area, "Chỉ bán #{current_user.area.name} sau 22:30?" %><br/>
          <label class="switch">
            <%= form.check_box :auto_close %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div class="col-sm-5" style="padding-left: 50px">
        <div class="field" data-length="<%= areas.length %>" id="length">
          <% areas.each do |area| %>
            <%= form.fields_for :areas_products,
              area.area_ids_of_product(product) ||
              product.areas_products.build do |ap| %>
              <%= form.label area.name, style: "text-transform: uppercase;" %>
              <%= ap.check_box :area_id, {id: "checkbox_check#{area.id}",
                class: "checkbox2"}, area.id, 0 %>
              <%= ap.hidden_field :_destroy, id: "data-form-prepend#{area.id}" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="col-sm-6 pull-time">
        <div class="field" style="float:left; padding-right: 137px;">
          <%= form.label :begin_at, "Thời gian mở cửa" %><br/>
          <%= form.time_select :begin_at, class: "form-control time_select" %>
        </div>

        <div class="field">
          <%= form.label :finish_at, "Thời gian đóng cửa" %><br/>
          <%= form.time_select :finish_at, class: "form-control time_select" %>
        </div>
    </div>
    <div class="row" style="padding-left: 30px;">
      <div class="actions">
        <%= link_to t("back"), products_path,
          class: "btn btn-add1" %>
        <%= form.submit t("submit"),
            class: "btn btn-add", id: "merge_button" %>
      </div>
    </div>

  <% end %>
  </div>
</div>
<script>
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
            $('#imagePreview').css('background-image', 'url('+e.target.result +')');
            $('#imagePreview').hide();
            $('#imagePreview').fadeIn(650);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#imageUpload").change(function() {
    readURL(this);
});
</script>

app/views/products/edit.html.erb
<div class="left-sidebar">
  <h2 style="font-size: 24px; font-family: lato;">Chỉnh sửa</h2>
</div>

<%= render "form", product: @product, areas: @areas %>
<br/>

app/views/products/index.html.erb
<% if can? :new, Product %>
  <a class="btn btn-add pull-right" href="<%= new_product_path %>">
    <span class="fa fa-plus-square"> Tạo mới</span>
  </a>
<% end %>
<div class="container">
  <div class="row">
    <div class="flat-projects">
      <ul class="projects-filter style1">
        <li class="active"><a data-filter="*" href="#">All</a></li>
        <% @categories.each do |category| %>
          <li><%= link_to category.name, "#",
            data: {filter: ".#{category.id}"} %></li>
        <% end %>
      </ul>
      <div class="projects-items">
        <% @products.each do |product| %>
            <div class="projects flat-column-4 hentry <%= product.category.id %>">
              <div class="project-wrap size">
                <div class="project-thumbnail">
                    <%= image_tag product.picture.url if product.picture? %>
                </div>
                <div class="">
                  <div class="">
                    <h3 class="center tittle">
                      <%= link_to product.name, product %>
                    </h3>
                    <p class="center"><%= link_to number_with_delimiter(product.price), product %>VNĐ</p>
                    <h6 class="center">
                      <% if cannot? :update, product %>
                        <%= link_to '<i class="fa fa-shopping-cart"> Buy</i>'.html_safe,
                        product_order_details_path(product), method: :post, class: "btn btn-add" %>
                      <% end %>
                    </h6>
                  </div>
                </div>
              </div><!-- /.project-wrap -->
            </div><!-- /.hentry -->
        <% end %>
      </div><!-- /.projects-items -->
    </div>
  </div>
</div>

app/views/products/new.html.erb
  <div class="left-sidebar">
    <h2 style="font-size: 24px; font-family: lato;">Tạo mới</h2>
  </div>
    <%= render "form", product: @product, areas: @areas %><br/>

app/views/products/show.html.erb
<div class="line">
  <div class="picture-show col-sm-7">
    <%= image_tag @product.picture.url if @product.picture? %></div>
    <div class="col-sm-4">
      <div class="unit5">
        <p class="name"><strong><%= @product.name %></strong></p>
        <p class="name1"><strong><%= number_with_delimiter(@product.price) %> VNĐ</strong></p>
        <p class="area" style="font-size: 16px;">
          <%= @product.begin_at.strftime("%I:%M %p") %> - <%= @product.finish_at.strftime("%I:%M %p") %>
        </p>
        <p>
          <% @product.areas.each do |area| %>
            <strong class="area">
              <%= area.name %>
            </strong>
          <% end %>
        </p>
        <% if cannot? :update, @product %>
          <%= link_to '<i class="fa fa-shopping-cart"> Buy</i>'.html_safe,
                        product_order_details_path(@product), method: :post, class: "btn btn-add" %>
        <% end %>
        <% if can? :update, @product %>
          <td><%= link_to "Chỉnh sửa",
            edit_product_path(@product), class: "btn btn-add", style: "background: #333" %></td>
          <td><%= link_to "Xóa", @product,
            method: :delete, data: {confirm: t("confirm")},
            class: "btn btn-add", style: "background: #fa3600" %>
          </td>
        <% end %>
      </div>
    </div>
  </div>
</div>